
import { Schema, model, Document } from 'mongoose';

export interface ISmartCollection extends Document {
    userId: string;
    name: string;
    description?: string;
    articles: string[]; // List of articleIds
    isAutoGenerated: boolean;
    topic?: string;
    visibility: 'private' | 'public';
    allowSharing: boolean;
    createdAt: Date;
    updatedAt: Date;
}

const smartCollectionSchema = new Schema<ISmartCollection>(
    {
        userId: { type: String, required: true, index: true },
        name: { type: String, required: true },
        description: { type: String },
        articles: { type: [String], default: [] },
        isAutoGenerated: { type: Boolean, default: false },
        topic: { type: String },
        visibility: {
            type: String,
            enum: ['private', 'public'],
            default: 'private'
        },
        allowSharing: { type: Boolean, default: false },
    },
    { timestamps: true }
);

smartCollectionSchema.index({ userId: 1, topic: 1 }); // Quick lookup for auto-groups

export const SmartCollection = model<ISmartCollection>('SmartCollection', smartCollectionSchema);
